apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure/kustomize/overlays/staging/
    repoURL: 'https://github.com/markday1962/argocd-demo.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
